assignment2(3)/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using assignment2_3_.Data;
using assignment2_3_.Models;

namespace assignment2_3_.Controllers
{
    public class CategoriesController : Controller
    {
        private assignment2_3_Context db = new assignment2_3_Context();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

assignment2(3)/Controllers/ClothingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using assignment2_3_.Data;
using assignment2_3_.Models;
using assignment2_3_.ViewModels;
using PagedList;

namespace assignment2_3_.Controllers
{
    public class ClothingsController : Controller
    {
        private assignment2_3_Context db = new assignment2_3_Context();

        // GET: Clothings
        public ActionResult Index(string category, string search,int? page)
        {
            ClothingIndexViewModel viewModel = new ClothingIndexViewModel();

            var clothings = db.Clothings.Include(p => p.Category);
            if (!String.IsNullOrEmpty(search))
            {
                clothings = clothings.Where(p => p.Name.Contains(search) ||
                p.Type.Contains(search) ||
                p.Category.Name.Contains(search));
                /*ViewBag.Search = search;*/
                viewModel.Search = search;
            }
            viewModel.CatsWithCount = from matchingClothing in clothings
                                      where
                                      matchingClothing.CategoryID != null
                                      group matchingClothing by
                                      matchingClothing.Category.Name into
                                      catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          ClothingCount = catGroup.Count()
                                      };
            /*var categories = clothings.OrderBy(p => p.Category.Name).Select(p
           => p.Category.Name).Distinct();*/
            if (!String.IsNullOrEmpty(category))
            {
                clothings = clothings.Where(p => p.Category.Name == category);
                viewModel.Category= category;
            }
            clothings = clothings.OrderBy(p => p.Name);
            const int PageItems = 6;
            int currentPage = (page ?? 1);
            viewModel.Clothings = clothings.ToPagedList(currentPage, PageItems);
            /*ViewBag.Category = new SelectList(categories);
            return View(clothings.ToList());*/
            /*viewModel.Clothings = clothings;*/
            return View(viewModel);
        }

        // GET: Clothings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clothing clothing = db.Clothings.Find(id);
            if (clothing == null)
            {
                return HttpNotFound();
            }
            return View(clothing);
        }

        // GET: Clothings/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: Clothings/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,Type,CategoryID")] Clothing clothing)
        {
            if (ModelState.IsValid)
            {
                db.Clothings.Add(clothing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", clothing.CategoryID);
            return View(clothing);
        }

        // GET: Clothings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clothing clothing = db.Clothings.Find(id);
            if (clothing == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", clothing.CategoryID);
            return View(clothing);
        }

        // POST: Clothings/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,Type,CategoryID")] Clothing clothing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clothing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", clothing.CategoryID);
            return View(clothing);
        }

        // GET: Clothings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clothing clothing = db.Clothings.Find(id);
            if (clothing == null)
            {
                return HttpNotFound();
            }
            return View(clothing);
        }

        // POST: Clothings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Clothing clothing = db.Clothings.Find(id);
            db.Clothings.Remove(clothing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

assignment2(3)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div id="topic">
        <p>
            <b>Love yourself, start with new clothes</b>
        </p>
    </div>

    <nav id="nav" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切换导航" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1" >
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Category", "index", "Categories", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Clothing", "index", "Clothings", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>

                @using (Html.BeginForm("Index", "Clothings", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                {
                    <div class="form-group">
                        <div class="input-group">
                            <!-- 使用input group包裹搜索框和按钮 -->
                            @Html.TextBox("Search", null, new { @class = "form-control", @placeholder = "Search" })
                            <span class="input-group-btn" style="margin-left: 10px;">
                                <!-- input group 按钮 -->
                                <button type="submit" class="btn btn-secondary">Submit</button>
                            </span>
                        </div>
                    </div>
                }
            </div>
        </div>
    </nav>
    <div id="imageLeft">
        <p><img width="100%" height="500" alt="Cycle Pathology" src="~/Content/Images/image1.jpg" /></p>
    </div>

    <div class="container body-content">
        @RenderBody()
        
    </div>

    <footer id="contact" style="margin-bottom: -100%;" >
        <hr />
        Contact us:<br />
        email:<a href="mailto:123456789.com">123456789.com</a>.<br>
        phone:<a href="tel:1234567890">1234567890</a>.<br>
        Written by Yuxin Yang-22009115.<br>
        Visit us at: Hebei University of Technology<br>.<br />
        <p>&copy; @DateTime.Now.Year - Dress freely and showcase your beauty</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>